FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore src/Apps/CenteralES.Web/CenteralES.Web.csproj
RUN dotnet publish src/Apps/CenteralES.Web/CenteralES.Web.csproj \
    --configuration Release \
    --no-restore \
    --output /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
EXPOSE 8080

RUN mkdir -p /var/lib/centerales/temporary-files \
    && chown -R app:app /var/lib/centerales
COPY --from=build /app/publish .
USER app
ENTRYPOINT ["dotnet", "CenteralES.Web.dll"]
